const data = {
  DESKTOP: {
    "2020-10-02": {
      total_brand: 2,
      total_brand_share: 0.4,
      total_non_brand: 3,
      total_non_brand_share: 0.6,
      total_total: 5,
      yandex_brand: 2,
      yandex_brand_share: 0.4,
      yandex_non_brand: 3,
      yandex_non_brand_share: 0.6,
      yandex_total: 5,
    },
    "2020-10-03": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 2,
      total_non_brand_share: 1,
      total_total: 2,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 2,
      yandex_non_brand_share: 1,
      yandex_total: 2,
    },
    "2020-10-05": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-08": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-10": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-13": {
      total_brand: 1,
      total_brand_share: 1,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 1,
      yandex_brand: 1,
      yandex_brand_share: 1,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 1,
    },
    "2020-10-14": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-15": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 2,
      total_non_brand_share: 1,
      total_total: 2,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 2,
      yandex_non_brand_share: 1,
      yandex_total: 2,
    },
    "2020-10-16": {
      total_brand: 2,
      total_brand_share: 1,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 2,
      yandex_brand: 2,
      yandex_brand_share: 1,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 2,
    },
    "2020-10-17": {
      total_brand: 1,
      total_brand_share: 1,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 1,
      yandex_brand: 1,
      yandex_brand_share: 1,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 1,
    },
    "2020-10-18": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-19": {
      total_brand: 1,
      total_brand_share: 0.33,
      total_non_brand: 2,
      total_non_brand_share: 0.67,
      total_total: 3,
      yandex_brand: 1,
      yandex_brand_share: 0.33,
      yandex_non_brand: 2,
      yandex_non_brand_share: 0.67,
      yandex_total: 3,
    },
  },
  MOBILE: {
    "2020-10-02": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-03": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-05": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 1,
      total_non_brand_share: 1,
      total_total: 1,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 1,
      yandex_non_brand_share: 1,
      yandex_total: 1,
    },
    "2020-10-08": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-10": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-13": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 1,
      total_non_brand_share: 1,
      total_total: 1,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 1,
      yandex_non_brand_share: 1,
      yandex_total: 1,
    },
    "2020-10-14": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-15": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-16": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-17": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-18": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
    "2020-10-19": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 0,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 0,
    },
  },
  TABLET: {
    "2020-10-02": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-03": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-05": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-08": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-10": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-13": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-14": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-15": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-16": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-17": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
    "2020-10-18": {
      total_brand_share: 0,
      total_non_brand: 1,
      total_non_brand_share: 1,
      total_total: 1,
      yandex_brand_share: 0,
      yandex_non_brand: 1,
      yandex_non_brand_share: 1,
      yandex_total: 1,
    },
    "2020-10-19": {
      total_brand_share: 0,
      total_non_brand: 0,
      total_non_brand_share: 1,
      total_total: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 0,
      yandex_non_brand_share: 1,
      yandex_total: 0,
    },
  },
  TOTAL: {
    "2020-10-02": {
      total_brand: 2,
      total_brand_share: 0.4,
      total_non_brand: 3,
      total_non_brand_share: 0.6,
      total_total: 5,
      yandex_brand: 2,
      yandex_brand_share: 0.4,
      yandex_non_brand: 3,
      yandex_non_brand_share: 0.6,
      yandex_total: 5,
    },
    "2020-10-03": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 2,
      total_non_brand_share: 1,
      total_total: 2,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 2,
      yandex_non_brand_share: 1,
      yandex_total: 2,
    },
    "2020-10-05": {
      total_brand: 1,
      total_brand_share: 0.33,
      total_non_brand: 2,
      total_non_brand_share: 0.67,
      total_total: 3,
      yandex_brand: 1,
      yandex_brand_share: 0.33,
      yandex_non_brand: 2,
      yandex_non_brand_share: 0.67,
      yandex_total: 3,
    },
    "2020-10-08": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-10": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-13": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-14": {
      total_brand: 1,
      total_brand_share: 0.5,
      total_non_brand: 1,
      total_non_brand_share: 0.5,
      total_total: 2,
      yandex_brand: 1,
      yandex_brand_share: 0.5,
      yandex_non_brand: 1,
      yandex_non_brand_share: 0.5,
      yandex_total: 2,
    },
    "2020-10-15": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 2,
      total_non_brand_share: 1,
      total_total: 2,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 2,
      yandex_non_brand_share: 1,
      yandex_total: 2,
    },
    "2020-10-16": {
      total_brand: 2,
      total_brand_share: 1,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 2,
      yandex_brand: 2,
      yandex_brand_share: 1,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 2,
    },
    "2020-10-17": {
      total_brand: 1,
      total_brand_share: 1,
      total_non_brand: 0,
      total_non_brand_share: 0,
      total_total: 1,
      yandex_brand: 1,
      yandex_brand_share: 1,
      yandex_non_brand: 0,
      yandex_non_brand_share: 0,
      yandex_total: 1,
    },
    "2020-10-18": {
      total_brand: 0,
      total_brand_share: 0,
      total_non_brand: 1,
      total_non_brand_share: 1,
      total_total: 1,
      yandex_brand: 0,
      yandex_brand_share: 0,
      yandex_non_brand: 1,
      yandex_non_brand_share: 1,
      yandex_total: 1,
    },
    "2020-10-19": {
      total_brand: 1,
      total_brand_share: 0.33,
      total_non_brand: 2,
      total_non_brand_share: 0.67,
      total_total: 3,
      yandex_brand: 1,
      yandex_brand_share: 0.33,
      yandex_non_brand: 2,
      yandex_non_brand_share: 0.67,
      yandex_total: 3,
    },
  },
}

function transfer(data) {
  const table = {}
  for (let key in data) {
    let rows = Object.keys(Object.values(data[key])[0])
    table[key] = []
    for (let item of rows) {
      let obj = {}
      obj.name = item
      for (let date in data[key]) {
        obj[date] = data[key][date][item]
      }
      table[key].push(obj)
    }
  }
  return table
}


console.log(JSON.stringify(transfer(data), null, 2))

const firstDate = Object.keys(desktop)[0];
const rows = Object.keys(desktop[firstDate])
const transform = {}

for (let row of rows) {
  transform[row] = {}
  for (let key in desktop) {
    transform[row][key] = desktop[key][row]
  }
}

console.log(transform)
